-- =====================================================================
-- 032_adaptive_ui.sql  --  OBSOLETE / NO-OP
-- =====================================================================
-- The Adaptive UI feature was migrated off Supabase entirely to avoid
-- consuming the project's Supabase API call quota.
--
--   * Telemetry ingest now goes directly from the browser to a
--     Cloudflare Worker (./ui-telemetry/) that writes to Cloudflare
--     Analytics Engine.
--   * Aggregation runs as a SQL HTTP query against Analytics Engine
--     from backend/ui_events_api.py (no Postgres reads).
--   * Layout decisions are persisted to a local JSON file
--     (UI_DECISIONS_FILE) on the backend host, not to Postgres.
--
-- This file is intentionally a no-op so the migrations directory keeps
-- a stable sequence. The previous tables (ui_events, layout_decisions,
-- layout_history, cohort_attention_map) and the helper function
-- refresh_cohort_map_if_stale() are NO LONGER created.
--
-- If a prior version of this migration already ran on your database
-- and you want to reclaim space, you may DROP the artifacts manually:
--
--   DROP MATERIALIZED VIEW IF EXISTS cohort_attention_map;
--   DROP TABLE IF EXISTS layout_history;
--   DROP TABLE IF EXISTS layout_decisions;
--   DROP TABLE IF EXISTS ui_events;
--   DROP FUNCTION IF EXISTS refresh_cohort_map_if_stale(INT);
--
-- The DROPs are intentionally NOT executed automatically here so that
-- re-running migrations is non-destructive.
-- =====================================================================

SELECT 1;
